apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
          ports:
            - containerPort: 8501
          env:
            - name: MCP_API_URL
              value: "{{ .Values.env.MCP_API_URL }}"
            - name: PROMETHEUS_URL
              value: "{{ .Values.env.PROMETHEUS_URL }}"
            - name: LLM_URL
              value: "{{ .Values.env.LLM_URL }}"
            - name: LLM_API_TOKEN
              value: "{{ .Values.env.LLM_API_TOKEN }}"